// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ7Qd9k5tPe2U-zxVSKiokSPE653tfZro',
    appId: '1:915556290959:web:68d81ba38d23c4033c3bfa',
    messagingSenderId: '915556290959',
    projectId: 'komeet-6caca',
    authDomain: 'komeet-6caca.firebaseapp.com',
    storageBucket: 'komeet-6caca.firebasestorage.app',
    measurementId: 'G-13J13GZXK4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNh5sr3nwWhBZCmNSXFxxI7ADgL-m4z7Q',
    appId: '1:915556290959:android:12481d9dcd1448af3c3bfa',
    messagingSenderId: '915556290959',
    projectId: 'komeet-6caca',
    storageBucket: 'komeet-6caca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKbKaf5CUkQhzzjsvmaM35kMxib9V1VeQ',
    appId: '1:915556290959:ios:8d09fdde969d4cd73c3bfa',
    messagingSenderId: '915556290959',
    projectId: 'komeet-6caca',
    storageBucket: 'komeet-6caca.firebasestorage.app',
    iosBundleId: 'com.example.komeet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ7Qd9k5tPe2U-zxVSKiokSPE653tfZro',
    appId: '1:915556290959:web:18fd9453dfcd9d0f3c3bfa',
    messagingSenderId: '915556290959',
    projectId: 'komeet-6caca',
    authDomain: 'komeet-6caca.firebaseapp.com',
    storageBucket: 'komeet-6caca.firebasestorage.app',
    measurementId: 'G-DY364FR00Y',
  );

}